# Created by: Hondareyte <lhondareyte@laposte.net>
# $FreeBSD$

PORTNAME=	spectro-utils
PORTVERSION=	1.0
CATEGORIES=	sysutils

MAINTAINER=	lhondareyte@laposte.net
WWW=		http://lhondareyte.free.fr/spectro-450
COMMENT=	SPECTRO-450 audio appliance utilities

LEGAL_PACKAGE=	yes
LICENSE=	BSD2CLAUSE
NO_LICENSES_INSTALL=yes

MASTER_SITES=	GH
USE_GITHUB=	yes
GH_ACCOUNT=	lhondareyte
GH_PROJECT=	spectro-utils
GH_TAGNAME=	${PORTVERSION}

.include <bsd.port.mk>
