# Created by: Hondareyte

PORTNAME=	mmm
PORTVERSION=	0.3
PORTREVISION=	4
CATEGORIES=	audio
MASTER_SITES=	GH

MAINTAINER=	lhondareyte@isp.net.invalid
COMMENT=	Minimal MIDI monitor
WWW=		https://github.com/lhondareyte/mmm

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	lhondareyte
GH_PROJECT=	mmm
GH_TAGNAME=	98a3e4e
PLIST_FILES=	bin/mmm

.include <bsd.port.mk>
