# Created by: Luc Hondareyte

PORTNAME=	dvm1200
PORTVERSION=	1.1
#PORTREVISION=	2
CATEGORIES=	sysutils

MAINTAINER=	lhondareyte@isp.net.invalid
COMMENT=	CLI for VELLEMAN DVM1200
WWW= 		http://github.com/lhondareyte/dvm1200.git

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	lhondareyte
GH_PROJECT=	$(PORTNAME)
GH_TAGNAME=	4271dd1

PLIST_FILES=    bin/dvm1200 \
		share/man/man1/dvm1200.1.gz

.include <bsd.port.mk>
