# Created by: Hondareyte <lhondareyte@laposte.net>
# $FreeBSD$

PORTNAME=	cmm
PORTVERSION=	0.2a
CATEGORIES=	audio
MASTER_SITES=	GH

MAINTAINER=	lhondareyte@laposte.net
COMMENT=	Simple MIDI monitor

LICENSE=	BSD2CLAUSE

MAKEFILE=	BSDmakefile

USE_GITHUB=	yes
GH_ACCOUNT=	lhondareyte
GH_PROJECT=	mm
GH_TAGNAME=	${PORTVERSION}

.include <bsd.port.mk>
