# Created by: Hondareyte

PORTNAME=	pykwalify
PORTVERSION=	1.7.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lhondareyte@isp.net.invalid
COMMENT=	Python lib/cli for JSON/YAML schema validation
WWW=		http://www.kuwata-lab.com/kwalify/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
